<?xml version="1.0" encoding="utf-8"?><Database Name="CXSRETAIL61" Class="IvendDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress2008;Initial Catalog=CXSRETAIL61;Persist Security Info=True;User ID=sa" SettingsObjectName="ConsultaCrea_Cliente.Properties.Settings" SettingsPropertyName="CXSRETAIL61ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CusCustomer" Member="CusCustomers">
    <Type Name="CusCustomer">
      <Column Name="CustomerKey" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Salutation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddressKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BillingAddressKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ShippingAddressKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="HomeCurrencyKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WebPage" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LoyalityId" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="AccountingID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsTaxExempt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TaxNumber" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="CustomerGroupKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SalesTaxCodeKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="StoreKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OnHold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsMarketing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AlternatePhoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShippingTypeKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryContactKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsTemplate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequireRenter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequireSignature" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreditCardKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PriceListKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MultiCurrency" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasLoyaltyId" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerDiscount" Type="System.Decimal" DbType="Decimal(20,5) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTypeKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ElectronicId" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnniversaryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsLoyaltyMember" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanOrderItems" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TaxCompanyType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CusCustomer_CusCustomerGroup" Member="CusCustomerGroups" ThisKey="CustomerGroupKey" OtherKey="CustomerGroupKey" Type="CusCustomerGroup" />
    </Type>
  </Table>
  <Table Name="dbo.CusCustomerGroup" Member="CusCustomerGroups">
    <Type Name="CusCustomerGroup">
      <Column Name="CustomerGroupKey" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SalesTaxCodeKey" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CusCustomer_CusCustomerGroup" Member="CusCustomer" ThisKey="CustomerGroupKey" OtherKey="CustomerGroupKey" Type="CusCustomer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>