#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaCrea_Cliente.Model.datasource
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CXSRETAIL61")]
	public partial class IvendDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCusCustomer(CusCustomer instance);
    partial void UpdateCusCustomer(CusCustomer instance);
    partial void DeleteCusCustomer(CusCustomer instance);
    partial void InsertCusCustomerGroup(CusCustomerGroup instance);
    partial void UpdateCusCustomerGroup(CusCustomerGroup instance);
    partial void DeleteCusCustomerGroup(CusCustomerGroup instance);
    #endregion
		
		public IvendDBDataContext() : 
				base(global::ConsultaCrea_Cliente.Properties.Settings.Default.CXSRETAIL61ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IvendDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IvendDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IvendDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IvendDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CusCustomer> CusCustomers
		{
			get
			{
				return this.GetTable<CusCustomer>();
			}
		}
		
		public System.Data.Linq.Table<CusCustomerGroup> CusCustomerGroups
		{
			get
			{
				return this.GetTable<CusCustomerGroup>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CusCustomer")]
	public partial class CusCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CustomerKey;
		
		private string _Id;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _Salutation;
		
		private string _Title;
		
		private string _NickName;
		
		private string _CompanyName;
		
		private long _AddressKey;
		
		private long _BillingAddressKey;
		
		private long _ShippingAddressKey;
		
		private long _HomeCurrencyKey;
		
		private string _Email;
		
		private string _WebPage;
		
		private string _LoyalityId;
		
		private string _AccountingID;
		
		private bool _IsTaxExempt;
		
		private string _TaxNumber;
		
		private long _CustomerGroupKey;
		
		private long _SalesTaxCodeKey;
		
		private long _StoreKey;
		
		private bool _IsActive;
		
		private bool _OnHold;
		
		private bool _IsMarketing;
		
		private string _PhoneNumber;
		
		private string _AlternatePhoneNumber;
		
		private string _MobilePhone;
		
		private string _FaxNumber;
		
		private long _ShippingTypeKey;
		
		private long _PrimaryContactKey;
		
		private bool _IsTemplate;
		
		private bool _RequireRenter;
		
		private bool _RequireSignature;
		
		private long _CreditCardKey;
		
		private long _PriceListKey;
		
		private bool _MultiCurrency;
		
		private bool _HasLoyaltyId;
		
		private decimal _CustomerDiscount;
		
		private System.DateTime _Created;
		
		private long _CreatedBy;
		
		private System.DateTime _Modified;
		
		private long _ModifiedBy;
		
		private bool _IsDeleted;
		
		private long _PaymentTypeKey;
		
		private string _ElectronicId;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private System.Nullable<System.DateTime> _AnniversaryDate;
		
		private bool _IsLoyaltyMember;
		
		private bool _CanOrderItems;
		
		private int _TaxCompanyType;
		
		private EntitySet<CusCustomerGroup> _CusCustomerGroups;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerKeyChanging(long value);
    partial void OnCustomerKeyChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnSalutationChanging(string value);
    partial void OnSalutationChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnNickNameChanging(string value);
    partial void OnNickNameChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnAddressKeyChanging(long value);
    partial void OnAddressKeyChanged();
    partial void OnBillingAddressKeyChanging(long value);
    partial void OnBillingAddressKeyChanged();
    partial void OnShippingAddressKeyChanging(long value);
    partial void OnShippingAddressKeyChanged();
    partial void OnHomeCurrencyKeyChanging(long value);
    partial void OnHomeCurrencyKeyChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebPageChanging(string value);
    partial void OnWebPageChanged();
    partial void OnLoyalityIdChanging(string value);
    partial void OnLoyalityIdChanged();
    partial void OnAccountingIDChanging(string value);
    partial void OnAccountingIDChanged();
    partial void OnIsTaxExemptChanging(bool value);
    partial void OnIsTaxExemptChanged();
    partial void OnTaxNumberChanging(string value);
    partial void OnTaxNumberChanged();
    partial void OnCustomerGroupKeyChanging(long value);
    partial void OnCustomerGroupKeyChanged();
    partial void OnSalesTaxCodeKeyChanging(long value);
    partial void OnSalesTaxCodeKeyChanged();
    partial void OnStoreKeyChanging(long value);
    partial void OnStoreKeyChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnOnHoldChanging(bool value);
    partial void OnOnHoldChanged();
    partial void OnIsMarketingChanging(bool value);
    partial void OnIsMarketingChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnAlternatePhoneNumberChanging(string value);
    partial void OnAlternatePhoneNumberChanged();
    partial void OnMobilePhoneChanging(string value);
    partial void OnMobilePhoneChanged();
    partial void OnFaxNumberChanging(string value);
    partial void OnFaxNumberChanged();
    partial void OnShippingTypeKeyChanging(long value);
    partial void OnShippingTypeKeyChanged();
    partial void OnPrimaryContactKeyChanging(long value);
    partial void OnPrimaryContactKeyChanged();
    partial void OnIsTemplateChanging(bool value);
    partial void OnIsTemplateChanged();
    partial void OnRequireRenterChanging(bool value);
    partial void OnRequireRenterChanged();
    partial void OnRequireSignatureChanging(bool value);
    partial void OnRequireSignatureChanged();
    partial void OnCreditCardKeyChanging(long value);
    partial void OnCreditCardKeyChanged();
    partial void OnPriceListKeyChanging(long value);
    partial void OnPriceListKeyChanged();
    partial void OnMultiCurrencyChanging(bool value);
    partial void OnMultiCurrencyChanged();
    partial void OnHasLoyaltyIdChanging(bool value);
    partial void OnHasLoyaltyIdChanged();
    partial void OnCustomerDiscountChanging(decimal value);
    partial void OnCustomerDiscountChanged();
    partial void OnCreatedChanging(System.DateTime value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnModifiedChanging(System.DateTime value);
    partial void OnModifiedChanged();
    partial void OnModifiedByChanging(long value);
    partial void OnModifiedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnPaymentTypeKeyChanging(long value);
    partial void OnPaymentTypeKeyChanged();
    partial void OnElectronicIdChanging(string value);
    partial void OnElectronicIdChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateChanged();
    partial void OnAnniversaryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAnniversaryDateChanged();
    partial void OnIsLoyaltyMemberChanging(bool value);
    partial void OnIsLoyaltyMemberChanged();
    partial void OnCanOrderItemsChanging(bool value);
    partial void OnCanOrderItemsChanged();
    partial void OnTaxCompanyTypeChanging(int value);
    partial void OnTaxCompanyTypeChanged();
    #endregion
		
		public CusCustomer()
		{
			this._CusCustomerGroups = new EntitySet<CusCustomerGroup>(new Action<CusCustomerGroup>(this.attach_CusCustomerGroups), new Action<CusCustomerGroup>(this.detach_CusCustomerGroups));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerKey", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long CustomerKey
		{
			get
			{
				return this._CustomerKey;
			}
			set
			{
				if ((this._CustomerKey != value))
				{
					this.OnCustomerKeyChanging(value);
					this.SendPropertyChanging();
					this._CustomerKey = value;
					this.SendPropertyChanged("CustomerKey");
					this.OnCustomerKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(40)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salutation", DbType="NVarChar(50)")]
		public string Salutation
		{
			get
			{
				return this._Salutation;
			}
			set
			{
				if ((this._Salutation != value))
				{
					this.OnSalutationChanging(value);
					this.SendPropertyChanging();
					this._Salutation = value;
					this.SendPropertyChanged("Salutation");
					this.OnSalutationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="NVarChar(50)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this.OnNickNameChanging(value);
					this.SendPropertyChanging();
					this._NickName = value;
					this.SendPropertyChanged("NickName");
					this.OnNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(50)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressKey", DbType="BigInt NOT NULL")]
		public long AddressKey
		{
			get
			{
				return this._AddressKey;
			}
			set
			{
				if ((this._AddressKey != value))
				{
					this.OnAddressKeyChanging(value);
					this.SendPropertyChanging();
					this._AddressKey = value;
					this.SendPropertyChanged("AddressKey");
					this.OnAddressKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingAddressKey", DbType="BigInt NOT NULL")]
		public long BillingAddressKey
		{
			get
			{
				return this._BillingAddressKey;
			}
			set
			{
				if ((this._BillingAddressKey != value))
				{
					this.OnBillingAddressKeyChanging(value);
					this.SendPropertyChanging();
					this._BillingAddressKey = value;
					this.SendPropertyChanged("BillingAddressKey");
					this.OnBillingAddressKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddressKey", DbType="BigInt NOT NULL")]
		public long ShippingAddressKey
		{
			get
			{
				return this._ShippingAddressKey;
			}
			set
			{
				if ((this._ShippingAddressKey != value))
				{
					this.OnShippingAddressKeyChanging(value);
					this.SendPropertyChanging();
					this._ShippingAddressKey = value;
					this.SendPropertyChanged("ShippingAddressKey");
					this.OnShippingAddressKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeCurrencyKey", DbType="BigInt NOT NULL")]
		public long HomeCurrencyKey
		{
			get
			{
				return this._HomeCurrencyKey;
			}
			set
			{
				if ((this._HomeCurrencyKey != value))
				{
					this.OnHomeCurrencyKeyChanging(value);
					this.SendPropertyChanging();
					this._HomeCurrencyKey = value;
					this.SendPropertyChanged("HomeCurrencyKey");
					this.OnHomeCurrencyKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebPage", DbType="NVarChar(100)")]
		public string WebPage
		{
			get
			{
				return this._WebPage;
			}
			set
			{
				if ((this._WebPage != value))
				{
					this.OnWebPageChanging(value);
					this.SendPropertyChanging();
					this._WebPage = value;
					this.SendPropertyChanged("WebPage");
					this.OnWebPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoyalityId", DbType="NVarChar(40)")]
		public string LoyalityId
		{
			get
			{
				return this._LoyalityId;
			}
			set
			{
				if ((this._LoyalityId != value))
				{
					this.OnLoyalityIdChanging(value);
					this.SendPropertyChanging();
					this._LoyalityId = value;
					this.SendPropertyChanged("LoyalityId");
					this.OnLoyalityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountingID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountingID
		{
			get
			{
				return this._AccountingID;
			}
			set
			{
				if ((this._AccountingID != value))
				{
					this.OnAccountingIDChanging(value);
					this.SendPropertyChanging();
					this._AccountingID = value;
					this.SendPropertyChanged("AccountingID");
					this.OnAccountingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTaxExempt", DbType="Bit NOT NULL")]
		public bool IsTaxExempt
		{
			get
			{
				return this._IsTaxExempt;
			}
			set
			{
				if ((this._IsTaxExempt != value))
				{
					this.OnIsTaxExemptChanging(value);
					this.SendPropertyChanging();
					this._IsTaxExempt = value;
					this.SendPropertyChanged("IsTaxExempt");
					this.OnIsTaxExemptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxNumber", DbType="NVarChar(40)")]
		public string TaxNumber
		{
			get
			{
				return this._TaxNumber;
			}
			set
			{
				if ((this._TaxNumber != value))
				{
					this.OnTaxNumberChanging(value);
					this.SendPropertyChanging();
					this._TaxNumber = value;
					this.SendPropertyChanged("TaxNumber");
					this.OnTaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerGroupKey", DbType="BigInt NOT NULL")]
		public long CustomerGroupKey
		{
			get
			{
				return this._CustomerGroupKey;
			}
			set
			{
				if ((this._CustomerGroupKey != value))
				{
					this.OnCustomerGroupKeyChanging(value);
					this.SendPropertyChanging();
					this._CustomerGroupKey = value;
					this.SendPropertyChanged("CustomerGroupKey");
					this.OnCustomerGroupKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesTaxCodeKey", DbType="BigInt NOT NULL")]
		public long SalesTaxCodeKey
		{
			get
			{
				return this._SalesTaxCodeKey;
			}
			set
			{
				if ((this._SalesTaxCodeKey != value))
				{
					this.OnSalesTaxCodeKeyChanging(value);
					this.SendPropertyChanging();
					this._SalesTaxCodeKey = value;
					this.SendPropertyChanged("SalesTaxCodeKey");
					this.OnSalesTaxCodeKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreKey", DbType="BigInt NOT NULL")]
		public long StoreKey
		{
			get
			{
				return this._StoreKey;
			}
			set
			{
				if ((this._StoreKey != value))
				{
					this.OnStoreKeyChanging(value);
					this.SendPropertyChanging();
					this._StoreKey = value;
					this.SendPropertyChanged("StoreKey");
					this.OnStoreKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnHold", DbType="Bit NOT NULL")]
		public bool OnHold
		{
			get
			{
				return this._OnHold;
			}
			set
			{
				if ((this._OnHold != value))
				{
					this.OnOnHoldChanging(value);
					this.SendPropertyChanging();
					this._OnHold = value;
					this.SendPropertyChanged("OnHold");
					this.OnOnHoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMarketing", DbType="Bit NOT NULL")]
		public bool IsMarketing
		{
			get
			{
				return this._IsMarketing;
			}
			set
			{
				if ((this._IsMarketing != value))
				{
					this.OnIsMarketingChanging(value);
					this.SendPropertyChanging();
					this._IsMarketing = value;
					this.SendPropertyChanged("IsMarketing");
					this.OnIsMarketingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternatePhoneNumber", DbType="NVarChar(50)")]
		public string AlternatePhoneNumber
		{
			get
			{
				return this._AlternatePhoneNumber;
			}
			set
			{
				if ((this._AlternatePhoneNumber != value))
				{
					this.OnAlternatePhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._AlternatePhoneNumber = value;
					this.SendPropertyChanged("AlternatePhoneNumber");
					this.OnAlternatePhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePhone", DbType="NVarChar(50)")]
		public string MobilePhone
		{
			get
			{
				return this._MobilePhone;
			}
			set
			{
				if ((this._MobilePhone != value))
				{
					this.OnMobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._MobilePhone = value;
					this.SendPropertyChanged("MobilePhone");
					this.OnMobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNumber", DbType="NVarChar(50)")]
		public string FaxNumber
		{
			get
			{
				return this._FaxNumber;
			}
			set
			{
				if ((this._FaxNumber != value))
				{
					this.OnFaxNumberChanging(value);
					this.SendPropertyChanging();
					this._FaxNumber = value;
					this.SendPropertyChanged("FaxNumber");
					this.OnFaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingTypeKey", DbType="BigInt NOT NULL")]
		public long ShippingTypeKey
		{
			get
			{
				return this._ShippingTypeKey;
			}
			set
			{
				if ((this._ShippingTypeKey != value))
				{
					this.OnShippingTypeKeyChanging(value);
					this.SendPropertyChanging();
					this._ShippingTypeKey = value;
					this.SendPropertyChanged("ShippingTypeKey");
					this.OnShippingTypeKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryContactKey", DbType="BigInt NOT NULL")]
		public long PrimaryContactKey
		{
			get
			{
				return this._PrimaryContactKey;
			}
			set
			{
				if ((this._PrimaryContactKey != value))
				{
					this.OnPrimaryContactKeyChanging(value);
					this.SendPropertyChanging();
					this._PrimaryContactKey = value;
					this.SendPropertyChanged("PrimaryContactKey");
					this.OnPrimaryContactKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTemplate", DbType="Bit NOT NULL")]
		public bool IsTemplate
		{
			get
			{
				return this._IsTemplate;
			}
			set
			{
				if ((this._IsTemplate != value))
				{
					this.OnIsTemplateChanging(value);
					this.SendPropertyChanging();
					this._IsTemplate = value;
					this.SendPropertyChanged("IsTemplate");
					this.OnIsTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequireRenter", DbType="Bit NOT NULL")]
		public bool RequireRenter
		{
			get
			{
				return this._RequireRenter;
			}
			set
			{
				if ((this._RequireRenter != value))
				{
					this.OnRequireRenterChanging(value);
					this.SendPropertyChanging();
					this._RequireRenter = value;
					this.SendPropertyChanged("RequireRenter");
					this.OnRequireRenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequireSignature", DbType="Bit NOT NULL")]
		public bool RequireSignature
		{
			get
			{
				return this._RequireSignature;
			}
			set
			{
				if ((this._RequireSignature != value))
				{
					this.OnRequireSignatureChanging(value);
					this.SendPropertyChanging();
					this._RequireSignature = value;
					this.SendPropertyChanged("RequireSignature");
					this.OnRequireSignatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardKey", DbType="BigInt NOT NULL")]
		public long CreditCardKey
		{
			get
			{
				return this._CreditCardKey;
			}
			set
			{
				if ((this._CreditCardKey != value))
				{
					this.OnCreditCardKeyChanging(value);
					this.SendPropertyChanging();
					this._CreditCardKey = value;
					this.SendPropertyChanged("CreditCardKey");
					this.OnCreditCardKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceListKey", DbType="BigInt NOT NULL")]
		public long PriceListKey
		{
			get
			{
				return this._PriceListKey;
			}
			set
			{
				if ((this._PriceListKey != value))
				{
					this.OnPriceListKeyChanging(value);
					this.SendPropertyChanging();
					this._PriceListKey = value;
					this.SendPropertyChanged("PriceListKey");
					this.OnPriceListKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MultiCurrency", DbType="Bit NOT NULL")]
		public bool MultiCurrency
		{
			get
			{
				return this._MultiCurrency;
			}
			set
			{
				if ((this._MultiCurrency != value))
				{
					this.OnMultiCurrencyChanging(value);
					this.SendPropertyChanging();
					this._MultiCurrency = value;
					this.SendPropertyChanged("MultiCurrency");
					this.OnMultiCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasLoyaltyId", DbType="Bit NOT NULL")]
		public bool HasLoyaltyId
		{
			get
			{
				return this._HasLoyaltyId;
			}
			set
			{
				if ((this._HasLoyaltyId != value))
				{
					this.OnHasLoyaltyIdChanging(value);
					this.SendPropertyChanging();
					this._HasLoyaltyId = value;
					this.SendPropertyChanged("HasLoyaltyId");
					this.OnHasLoyaltyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerDiscount", DbType="Decimal(20,5) NOT NULL")]
		public decimal CustomerDiscount
		{
			get
			{
				return this._CustomerDiscount;
			}
			set
			{
				if ((this._CustomerDiscount != value))
				{
					this.OnCustomerDiscountChanging(value);
					this.SendPropertyChanging();
					this._CustomerDiscount = value;
					this.SendPropertyChanged("CustomerDiscount");
					this.OnCustomerDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime NOT NULL")]
		public System.DateTime Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified", DbType="DateTime NOT NULL")]
		public System.DateTime Modified
		{
			get
			{
				return this._Modified;
			}
			set
			{
				if ((this._Modified != value))
				{
					this.OnModifiedChanging(value);
					this.SendPropertyChanging();
					this._Modified = value;
					this.SendPropertyChanged("Modified");
					this.OnModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="BigInt NOT NULL")]
		public long ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTypeKey", DbType="BigInt NOT NULL")]
		public long PaymentTypeKey
		{
			get
			{
				return this._PaymentTypeKey;
			}
			set
			{
				if ((this._PaymentTypeKey != value))
				{
					this.OnPaymentTypeKeyChanging(value);
					this.SendPropertyChanging();
					this._PaymentTypeKey = value;
					this.SendPropertyChanged("PaymentTypeKey");
					this.OnPaymentTypeKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElectronicId", DbType="NVarChar(40)")]
		public string ElectronicId
		{
			get
			{
				return this._ElectronicId;
			}
			set
			{
				if ((this._ElectronicId != value))
				{
					this.OnElectronicIdChanging(value);
					this.SendPropertyChanging();
					this._ElectronicId = value;
					this.SendPropertyChanged("ElectronicId");
					this.OnElectronicIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnniversaryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnniversaryDate
		{
			get
			{
				return this._AnniversaryDate;
			}
			set
			{
				if ((this._AnniversaryDate != value))
				{
					this.OnAnniversaryDateChanging(value);
					this.SendPropertyChanging();
					this._AnniversaryDate = value;
					this.SendPropertyChanged("AnniversaryDate");
					this.OnAnniversaryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLoyaltyMember", DbType="Bit NOT NULL")]
		public bool IsLoyaltyMember
		{
			get
			{
				return this._IsLoyaltyMember;
			}
			set
			{
				if ((this._IsLoyaltyMember != value))
				{
					this.OnIsLoyaltyMemberChanging(value);
					this.SendPropertyChanging();
					this._IsLoyaltyMember = value;
					this.SendPropertyChanged("IsLoyaltyMember");
					this.OnIsLoyaltyMemberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanOrderItems", DbType="Bit NOT NULL")]
		public bool CanOrderItems
		{
			get
			{
				return this._CanOrderItems;
			}
			set
			{
				if ((this._CanOrderItems != value))
				{
					this.OnCanOrderItemsChanging(value);
					this.SendPropertyChanging();
					this._CanOrderItems = value;
					this.SendPropertyChanged("CanOrderItems");
					this.OnCanOrderItemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCompanyType", DbType="Int NOT NULL")]
		public int TaxCompanyType
		{
			get
			{
				return this._TaxCompanyType;
			}
			set
			{
				if ((this._TaxCompanyType != value))
				{
					this.OnTaxCompanyTypeChanging(value);
					this.SendPropertyChanging();
					this._TaxCompanyType = value;
					this.SendPropertyChanged("TaxCompanyType");
					this.OnTaxCompanyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CusCustomer_CusCustomerGroup", Storage="_CusCustomerGroups", ThisKey="CustomerGroupKey", OtherKey="CustomerGroupKey")]
		public EntitySet<CusCustomerGroup> CusCustomerGroups
		{
			get
			{
				return this._CusCustomerGroups;
			}
			set
			{
				this._CusCustomerGroups.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CusCustomerGroups(CusCustomerGroup entity)
		{
			this.SendPropertyChanging();
			entity.CusCustomer = this;
		}
		
		private void detach_CusCustomerGroups(CusCustomerGroup entity)
		{
			this.SendPropertyChanging();
			entity.CusCustomer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CusCustomerGroup")]
	public partial class CusCustomerGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CustomerGroupKey;
		
		private string _Id;
		
		private string _Description;
		
		private long _SalesTaxCodeKey;
		
		private System.DateTime _Created;
		
		private long _CreatedBy;
		
		private System.DateTime _Modified;
		
		private long _ModifiedBy;
		
		private bool _IsDeleted;
		
		private bool _IsDefault;
		
		private EntityRef<CusCustomer> _CusCustomer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerGroupKeyChanging(long value);
    partial void OnCustomerGroupKeyChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSalesTaxCodeKeyChanging(long value);
    partial void OnSalesTaxCodeKeyChanged();
    partial void OnCreatedChanging(System.DateTime value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnModifiedChanging(System.DateTime value);
    partial void OnModifiedChanged();
    partial void OnModifiedByChanging(long value);
    partial void OnModifiedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnIsDefaultChanging(bool value);
    partial void OnIsDefaultChanged();
    #endregion
		
		public CusCustomerGroup()
		{
			this._CusCustomer = default(EntityRef<CusCustomer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerGroupKey", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long CustomerGroupKey
		{
			get
			{
				return this._CustomerGroupKey;
			}
			set
			{
				if ((this._CustomerGroupKey != value))
				{
					if (this._CusCustomer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerGroupKeyChanging(value);
					this.SendPropertyChanging();
					this._CustomerGroupKey = value;
					this.SendPropertyChanged("CustomerGroupKey");
					this.OnCustomerGroupKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesTaxCodeKey", DbType="BigInt NOT NULL")]
		public long SalesTaxCodeKey
		{
			get
			{
				return this._SalesTaxCodeKey;
			}
			set
			{
				if ((this._SalesTaxCodeKey != value))
				{
					this.OnSalesTaxCodeKeyChanging(value);
					this.SendPropertyChanging();
					this._SalesTaxCodeKey = value;
					this.SendPropertyChanged("SalesTaxCodeKey");
					this.OnSalesTaxCodeKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime NOT NULL")]
		public System.DateTime Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified", DbType="DateTime NOT NULL")]
		public System.DateTime Modified
		{
			get
			{
				return this._Modified;
			}
			set
			{
				if ((this._Modified != value))
				{
					this.OnModifiedChanging(value);
					this.SendPropertyChanging();
					this._Modified = value;
					this.SendPropertyChanged("Modified");
					this.OnModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="BigInt NOT NULL")]
		public long ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefault", DbType="Bit NOT NULL")]
		public bool IsDefault
		{
			get
			{
				return this._IsDefault;
			}
			set
			{
				if ((this._IsDefault != value))
				{
					this.OnIsDefaultChanging(value);
					this.SendPropertyChanging();
					this._IsDefault = value;
					this.SendPropertyChanged("IsDefault");
					this.OnIsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CusCustomer_CusCustomerGroup", Storage="_CusCustomer", ThisKey="CustomerGroupKey", OtherKey="CustomerGroupKey", IsForeignKey=true)]
		public CusCustomer CusCustomer
		{
			get
			{
				return this._CusCustomer.Entity;
			}
			set
			{
				CusCustomer previousValue = this._CusCustomer.Entity;
				if (((previousValue != value) 
							|| (this._CusCustomer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CusCustomer.Entity = null;
						previousValue.CusCustomerGroups.Remove(this);
					}
					this._CusCustomer.Entity = value;
					if ((value != null))
					{
						value.CusCustomerGroups.Add(this);
						this._CustomerGroupKey = value.CustomerGroupKey;
					}
					else
					{
						this._CustomerGroupKey = default(long);
					}
					this.SendPropertyChanged("CusCustomer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
